import {chromium} from 'playwright'
import assert from 'node:assert/strict'
import {createServer} from 'node:http'
import {readFile,writeFile,mkdir} from 'node:fs/promises'
import path from 'node:path'
const vendor=await readFile('vendor/metal-fx/index.es.js','utf8')
const fragment=vendor.slice(vendor.indexOf('  precision highp float;'),vendor.indexOf('\n`\n);')).replaceAll('\\`','`').trim()
const root=path.resolve('docs/demo')
const server=createServer(async(req,res)=>{try{const p=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!p.startsWith(root+path.sep)&&p!==root)throw Error();const file=p===root?path.join(root,'index.html'):p;res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html','.webp':'image/webp'})[path.extname(file)]||'application/octet-stream');res.end(await readFile(file))}catch{res.statusCode=404;res.end()}})
await new Promise(r=>server.listen(0,'127.0.0.1',r))
const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']})
const page=await browser.newPage({viewport:{width:1280,height:850}})
const errors=[];page.on('pageerror',e=>errors.push(e.message))
try{
 await page.goto(`http://127.0.0.1:${server.address().port}/`)
 await page.getByRole('tab',{name:'Lyrics',exact:true}).waitFor()
 await page.waitForTimeout(4800)
 const calls=await page.evaluate(()=>window.demoCalls.filter(x=>x.action==='status').length)
 assert.equal(calls,2,'pane and footer must share one four-second status poll')
 const artBox=await page.locator('#player-pane img').first().boundingBox()
 assert.ok(artBox.height<=192,'expanded artwork must not dominate the pane')
 const tabs=await page.getByRole('tablist').boundingBox()
 assert.ok(tabs.height<=28,'view tabs must be a quiet compact row')
 const volumeBox=await page.getByRole('slider',{name:'Spotify volume',exact:true}).boundingBox()
 assert.ok(volumeBox.width<=108,'volume must not look like a second full-width timeline')
 await page.getByRole('button',{name:'Pause Spotify',exact:true}).first().click()
 await page.getByRole('button',{name:'Play Spotify',exact:true}).first().waitFor()
 assert.equal(await page.getByRole('button',{name:'Play Spotify',exact:true}).count(),2,'command must synchronize both surfaces')
 assert.equal(await page.locator('.spotify-metal canvas').count(),0)
 await page.getByRole('button',{name:'Play Spotify',exact:true}).first().click()
 await page.evaluate(()=>{window.drawCount=0;window.shaderSources=[];window.glBuffers=[];const source=WebGLRenderingContext.prototype.shaderSource;WebGLRenderingContext.prototype.shaderSource=function(shader,text){window.shaderSources.push(text);return source.call(this,shader,text)};const draw=WebGLRenderingContext.prototype.drawArrays;WebGLRenderingContext.prototype.drawArrays=function(...args){window.drawCount++;window.glBuffers.push([this.drawingBufferWidth,this.drawingBufferHeight]);return draw.apply(this,args)}})
 await page.getByRole('button',{name:'Enable visual effects',exact:true}).click()
 await page.locator('.spotify-metal canvas').waitFor()
 const buffer=await page.locator('.spotify-metal canvas').evaluate(c=>({width:c.width,height:c.height}))
 assert.ok(buffer.width<=40&&buffer.height<=40,'metal ring must remain a small control overlay')
 assert.ok(await page.evaluate(expected=>window.shaderSources.some(s=>s.trim()===expected),fragment),'compiled fragment must exactly equal the vendored metal-fx shader')
 assert.ok(await page.evaluate(()=>window.glBuffers.every(([w,h])=>w<=96&&h<=96)),'shared GPU buffer capped at 96px and DPR 1')
 await page.evaluate(()=>{window.drawCount=0})
 await page.waitForTimeout(1100)
 const draws=await page.evaluate(()=>window.drawCount)
 assert.ok(draws>0&&draws<=15,'WebGL must stay at or below 12fps plus timing tolerance')
 assert.ok(await page.locator('.spotify-metal canvas').evaluate(c=>{const p=c.getContext('2d').getImageData(0,0,c.width,c.height).data;return p.some((v,i)=>i%4===3&&v>0)}),'actual metal ring must paint visible pixels')
 await page.locator('.product').screenshot({path:'docs/media/player-1.3-metal-fx.png'})
 await page.getByRole('button',{name:'Pause Spotify',exact:true}).first().evaluate(b=>{window.transportButton=b})
 await page.getByRole('button',{name:'Pause Spotify',exact:true}).first().click()
 await page.getByRole('button',{name:'Play Spotify',exact:true}).first().waitFor()
 assert.equal(await page.locator('.spotify-metal canvas').count(),0,'pausing releases the artifact')
 assert.equal(await page.getByRole('button',{name:'Play Spotify',exact:true}).first().evaluate(b=>b===window.transportButton),true,'effect cleanup must not replace the playback button')
 await page.getByRole('button',{name:'Play Spotify',exact:true}).first().click()
 await page.locator('.spotify-metal canvas').waitFor()
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.waitForTimeout(300)
 assert.equal(await page.locator('.spotify-metal canvas').count(),0)
 await page.emulateMedia({reducedMotion:'no-preference'})
 await page.getByRole('tab',{name:'Lyrics',exact:true}).click()
 await page.getByLabel('Synced lyrics').waitFor()
 await page.evaluate(()=>{window.rafCount=0;const original=window.requestAnimationFrame;window.requestAnimationFrame=function(fn){window.rafCount++;return original.call(this,fn)}})
 await page.waitForTimeout(1200)
 assert.ok(await page.evaluate(()=>window.rafCount)<10,'lyrics must not run a frame-rate loop')
 await page.evaluate(()=>{document.querySelector('#player-pane').style.position='absolute';document.querySelector('#player-pane').style.top='-3000px'})
 await page.waitForTimeout(250)
 assert.equal(await page.locator('.spotify-metal canvas').count(),0,'offscreen pane releases GPU')
 const offscreenDraws=await page.evaluate(()=>window.drawCount)
 await page.waitForTimeout(350)
 assert.equal(await page.evaluate(()=>window.drawCount),offscreenDraws,'offscreen artifact must stop GPU draws')
 await page.evaluate(()=>{document.querySelector('#player-pane').style.position='';document.querySelector('#player-pane').style.top=''})
 await page.getByRole('button',{name:'Compact',exact:true}).click()
 await page.waitForTimeout(300)
 assert.equal(await page.getByLabel('Synced lyrics').count(),0)
 await page.getByRole('button',{name:'Expanded',exact:true}).click()
 await page.getByRole('tab',{name:'Artwork',exact:true}).click()
 await page.getByRole('button',{name:'Disable visual effects',exact:true}).click()
 await page.getByRole('button',{name:'Standard',exact:true}).click()
 await page.evaluate(()=>{document.querySelector('.product').style.width='234px'})
 await page.waitForTimeout(300)
 assert.ok(await page.locator('#player-pane [title="After hours"]').first().evaluate(el=>el.getBoundingClientRect().width)>100,'title must remain legible in a 234px Hermes sidebar')
 assert.ok(await page.locator('#player-pane').evaluate(p=>{const r=p.getBoundingClientRect();return [...p.querySelectorAll('button,input')].every(e=>{const b=e.getBoundingClientRect();return b.bottom<=r.bottom+1&&b.right<=r.right+1&&b.left>=r.left-1})}),'all controls fit the 234px wide, 136px tall standard pane')
 await page.locator('.product').screenshot({path:'docs/media/player-1.3-standard.png'})
 await page.evaluate(()=>{document.querySelector('.product').style.width=''})
 await page.getByRole('button',{name:'Expanded',exact:true}).click()
 await page.getByRole('slider',{name:'Seek Spotify',exact:true}).focus()
 const seeksBefore=await page.evaluate(()=>window.demoCalls.filter(x=>x.action==='seek').length)
 await page.keyboard.press('ArrowRight')
 await page.waitForTimeout(300)
 assert.equal(await page.evaluate(()=>window.demoCalls.filter(x=>x.action==='seek').length),seeksBefore+1,'one command per seek commit')
 await page.getByRole('button',{name:'Enable visual effects',exact:true}).click()
 await page.locator('.spotify-metal canvas').waitFor()
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'))})
 await page.waitForTimeout(300)
 const hiddenStart=await page.evaluate(()=>window.demoCalls.filter(x=>x.action==='status').length)
 const hiddenDraws=await page.evaluate(()=>window.drawCount)
 assert.equal(await page.locator('.spotify-metal canvas').count(),0,'background document releases artifact')
 await page.waitForTimeout(4500)
 assert.equal(await page.evaluate(()=>window.demoCalls.filter(x=>x.action==='status').length),hiddenStart,'no status requests while document hidden')
 assert.equal(await page.evaluate(()=>window.drawCount),hiddenDraws,'no GPU frames while document hidden')
 await page.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'))})
 await page.waitForTimeout(300)
 await mkdir('docs/evidence',{recursive:true})
 await page.screenshot({path:'docs/media/player-1.3-desktop.png',fullPage:true})
 await page.setViewportSize({width:390,height:844})
 await page.screenshot({path:'docs/media/player-1.3-mobile.png',fullPage:true})
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'no horizontal overflow')
 const fallback=await browser.newPage()
 fallback.on('pageerror',e=>errors.push(e.message))
 await fallback.addInitScript(()=>{
   for(const proto of [HTMLCanvasElement.prototype,OffscreenCanvas.prototype]){
     const get=proto.getContext
     proto.getContext=function(type,...args){return /webgl/.test(type)?null:get.call(this,type,...args)}
   }
 })
 await fallback.goto(`http://127.0.0.1:${server.address().port}/`)
 await fallback.getByRole('button',{name:'Enable visual effects',exact:true}).click()
 await fallback.waitForTimeout(250)
 assert.equal(await fallback.locator('.spotify-metal canvas').count(),0,'unsupported GPU falls back without breaking the player')
 await fallback.getByRole('button',{name:'Pause Spotify',exact:true}).first().click()
 await fallback.getByRole('button',{name:'Play Spotify',exact:true}).first().waitFor()
 await fallback.close()
 assert.deepEqual(errors,[])
 await writeFile('docs/evidence/browser.json',JSON.stringify({status:'passed',statusCallsIn4800ms:calls,webglDrawsIn1100ms:draws,webglBuffer:buffer,artifact:'metal-fx@1.0.4',preset:'silver/dark',shaderExactMatch:true,webglSharedBufferMax:[96,96],hiddenStatusCallsIn4500ms:0,errors,checks:['shared polling','synchronized controls','opt-in WebGL','reduced motion','responsive resize','mobile overflow','offscreen GPU cleanup','seek commit','document visibility stop','WebGL frame/buffer budget','exact metal-fx shader provenance','painted ring pixels','pause/offscreen/background GPU stop','stable transport DOM','no-WebGL fallback']},null,2))
 console.log('Browser checks passed')
}catch(error){console.error('Page errors:',errors);await page.screenshot({path:'/tmp/spotify-browser-failure.png'});throw error}finally{await browser.close();server.close()}
