import {chromium} from 'playwright'
import assert from 'node:assert/strict'
import {createServer} from 'node:http'
import {readFile,writeFile,mkdir} from 'node:fs/promises'
import path from 'node:path'
const vendor=await readFile('vendor/metal-fx/index.es.js','utf8')
const fragment=vendor.slice(vendor.indexOf('  precision highp float;'),vendor.indexOf('\n`\n);')).replaceAll('\\`','`').trim()
const root=path.resolve('docs/demo')
// Preload a fixed asset set: request input never reaches a filesystem API.
const assets=new Map(await Promise.all([
 ['/', 'index.html', 'text/html'], ['/index.html', 'index.html', 'text/html'],
 ['/app.js', 'app.js', 'text/javascript'], ['/style.css', 'style.css', 'text/css'],
 ['/artwork.webp', 'artwork.webp', 'image/webp']
].map(async([url,file,type])=>[url,{body:await readFile(path.join(root,file)),type}])))
const server=createServer((req,res)=>{
 const asset=assets.get((req.url||'/').split('?')[0])
 if(!asset){res.statusCode=404;res.end();return}
 res.setHeader('Content-Type',asset.type);res.end(asset.body)
})
await new Promise(r=>server.listen(0,'127.0.0.1',r))
const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']})
const page=await browser.newPage({viewport:{width:1280,height:850}})
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(5000)
try{
 assert.equal((await fetch(`http://127.0.0.1:${server.address().port}/%61pp.js`)).status,404,'test server only serves exact allowlisted asset paths')
 await page.goto(`http://127.0.0.1:${server.address().port}/`)
 await page.getByRole('tab',{name:'Lyrics',exact:true}).waitFor()
 await page.waitForTimeout(4800)
 const calls=await page.evaluate(()=>window.demoCalls.filter(x=>x.action==='status').length)
 assert.equal(calls,2,'pane and footer must share one four-second status poll')
 await page.getByRole('button',{name:'Player settings',exact:true}).click()
 assert.equal(await page.locator('.spotify-screen [data-hardware]').count(),0,'settings must not duplicate physical controls in the display')
 assert.equal(await page.getByRole('button',{name:'Add current track to playlist',exact:true}).count(),1,'plus exists only once, on the shell')
 assert.equal(await page.getByRole('button',{name:'Like current track',exact:true}).count(),1,'heart exists only once, on the shell')
 await page.getByRole('radio',{name:'Ice blue',exact:true}).click()
 await page.locator('.product').screenshot({path:'docs/media/player-settings-in-screen.png'})
 await page.getByRole('button',{name:'Player settings',exact:true}).click()
 await page.locator('.spotify-surface').getByRole('button',{name:'Search Spotify',exact:true}).click()
 await page.locator('.spotify-screen').getByRole('textbox',{name:'Search Spotify',exact:true}).fill('After hours')
 await page.locator('.spotify-screen').getByRole('textbox',{name:'Search Spotify',exact:true}).press('Enter')
 await page.locator('.spotify-screen').getByRole('button',{name:'Play After hours by Studio session',exact:true}).waitFor()
 assert.equal(await page.getByRole('dialog').count(),0,'shell search must not escape into a modal')
 await page.locator('.product').screenshot({path:'docs/media/player-search-in-screen.png'})
 await page.getByRole('button',{name:'Add current track to playlist',exact:true}).click()
 await page.locator('.spotify-screen').getByRole('button',{name:'Add to Focus sessions',exact:true}).waitFor()
 assert.equal(await page.getByRole('dialog').count(),0,'playlist menu stays in the display')
 await page.locator('.product').screenshot({path:'docs/media/player-playlists-in-screen.png'})
 await page.getByRole('button',{name:'Player settings',exact:true}).click()
 await page.evaluate(()=>window.demoScenario['/auth/status']={response:{ok:true,loggedIn:false,clientConfigured:false}})
 await page.locator('.spotify-screen').getByRole('link',{name:'Spotify connection',exact:true}).click()
 await page.locator('.spotify-screen').getByRole('textbox',{name:'Spotify Client ID',exact:true}).waitFor()
 assert.equal(await page.getByRole('dialog').count(),0,'connection form stays in the display')
 await page.getByRole('tab',{name:'Artwork',exact:true}).click()
 assert.equal(await page.locator('.spotify-surface').getAttribute('data-finish'),'ice')
 await page.getByRole('button',{name:'Turn screen off',exact:true}).click()
 assert.equal(await page.locator('.spotify-screen').count(),0,'screen-off unmounts display resources')
 await page.waitForFunction(()=>document.querySelector('#player-pane').getBoundingClientRect().height<=140)
 const retainedHeight=await page.locator('#player-pane').evaluate(e=>e.getBoundingClientRect().height)
 assert.ok(retainedHeight<=140,'screen-off returns the reserved height to the host')
 await page.locator('.product').evaluate(e=>e.style.width='234px')
 await page.waitForFunction(()=>document.querySelector('.spotify-retro-stage').getBoundingClientRect().height<90)
 assert.ok(await page.locator('#player-pane').evaluate(e=>Math.abs(e.getBoundingClientRect().height-e.querySelector('.spotify-retro-stage').getBoundingClientRect().height)<=1),'narrow screen-off fits exact shell height')
 await page.locator('.product').evaluate(e=>e.style.width='340px')
 await page.waitForFunction(()=>document.querySelector('.spotify-retro-stage').getBoundingClientRect().height===112)
 assert.ok(await page.locator('#player-pane').evaluate(e=>Math.abs(e.getBoundingClientRect().height-e.querySelector('.spotify-retro-stage').getBoundingClientRect().height)<=1),'wide screen-off releases every unused pixel')
 const offBox=await page.locator('.spotify-surface').boundingBox()
 assert.ok(Math.abs(offBox.width/offBox.height-320/112)<.01,'screen-off is one uniformly scaled transport shell')
 await page.locator('.product').screenshot({path:'docs/media/player-screen-off.png'})
 // A shared tab group can be taller than Spotify's own requested height.
 // Reproduce the user's reserved sidebar, then grow it as a window resize would.
 const downward=[]
 for(const height of [300,420]){
  await page.locator('#player-group').evaluate((e,h)=>Object.assign(e.style,{height:`${h}px`,minHeight:`${h}px`,maxHeight:`${h}px`}),height)
  await page.waitForTimeout(100)
  const geometry=await page.locator('#player-pane').evaluate(e=>{const pane=e.getBoundingClientRect(),shell=e.querySelector('.spotify-retro-stage').getBoundingClientRect();return {paneBottom:pane.bottom,shellBottom:shell.bottom,top:shell.top,height:shell.height}})
  assert.ok(Math.abs(geometry.paneBottom-geometry.shellBottom)<=1,`compact player must follow pane bottom, not stick at its top: ${JSON.stringify(geometry)}`)
  assert.equal(geometry.height,112,'resizing reserved space must not stretch the shell')
  downward.push(geometry)
 }
 assert.ok(downward[1].top>downward[0].top,'player moves downward when the available pane grows')
 await page.locator('.product').screenshot({path:'docs/media/player-bottom-aligned.png'})
 await writeFile('docs/evidence/bottom-alignment.json',JSON.stringify(downward,null,2))

 await page.reload()
 await page.getByRole('button',{name:'Turn screen on',exact:true}).waitFor()
 assert.equal(await page.locator('.spotify-surface').getAttribute('data-finish'),'ice','skin and shell mode survive reload')
 await page.getByRole('button',{name:'Turn screen on',exact:true}).click()
 await page.waitForFunction(()=>document.querySelector('#player-pane').getBoundingClientRect().height>=205)
 const ratioBox=await page.locator('.spotify-surface').boundingBox()
 assert.ok(Math.abs(ratioBox.width/ratioBox.height-8/7)<0.005,'retro shell keeps its native 8:7 proportions')
 const chrome=await page.locator('.spotify-surface').evaluate(e=>{const s=getComputedStyle(e);return {height:e.getBoundingClientRect().height,finish:s.backgroundImage}})
 assert.ok(chrome.height<=280,'expanded chrome must stay bounded, not fill a large pane')
 assert.match(chrome.finish,/svg/,'the entire player must carry the material finish even with FX off')
 const artBox=await page.locator('#player-pane img').first().boundingBox()
 assert.ok(artBox.height<=160,'reference screen must stay within the bounded player')
 const tabs=await page.getByRole('tablist').boundingBox()
 assert.ok(tabs.width<=216,'view controls belong inside the screen bezel')
 const volumeBox=await page.getByRole('slider',{name:'Spotify volume',exact:true}).boundingBox()
 assert.ok(volumeBox.width<=108,'volume must not look like a second full-width timeline')
 await page.getByRole('button',{name:'Pause Spotify',exact:true}).first().click()
 await page.getByRole('button',{name:'Play Spotify',exact:true}).first().waitFor()
 assert.equal(await page.getByRole('button',{name:'Play Spotify',exact:true}).count(),2,'command must synchronize both surfaces')
 assert.equal(await page.locator('.spotify-metal canvas').count(),0)
 await page.evaluate(()=>{window.drawCount=0;window.shaderSources=[];window.glBuffers=[];const source=WebGLRenderingContext.prototype.shaderSource;WebGLRenderingContext.prototype.shaderSource=function(shader,text){window.shaderSources.push(text);return source.call(this,shader,text)};const draw=WebGLRenderingContext.prototype.drawArrays;WebGLRenderingContext.prototype.drawArrays=function(...args){window.drawCount++;window.glBuffers.push([this.drawingBufferWidth,this.drawingBufferHeight]);return draw.apply(this,args)}})
 await page.getByRole('button',{name:'Play Spotify',exact:true}).first().click()
 assert.equal(await page.getByRole('button',{name:/visual effects/i}).count(),0,'material effects are default')
 await page.locator('.spotify-metal canvas').waitFor()
 const buffer=await page.locator('.spotify-metal canvas').evaluate(c=>({width:c.width,height:c.height}))
 assert.ok(buffer.width<=48&&buffer.height<=48,'metal ring must remain a small control overlay')
 assert.ok(await page.evaluate(expected=>window.shaderSources.some(s=>s.trim()===expected),fragment),'compiled fragment must exactly equal the vendored metal-fx shader')
 assert.ok(await page.evaluate(()=>window.glBuffers.every(([w,h])=>w<=96&&h<=96)),'shared GPU buffer capped at 96px and DPR 1')
 await page.evaluate(()=>{window.drawCount=0})
 await page.waitForTimeout(1100)
 const draws=await page.evaluate(()=>window.drawCount)
 assert.ok(draws>0&&draws<=15,'WebGL must stay at or below 12fps plus timing tolerance')
 assert.ok(await page.locator('.spotify-metal canvas').evaluate(c=>{const p=c.getContext('2d').getImageData(0,0,c.width,c.height).data;return p.some((v,i)=>i%4===3&&v>0)}),'actual metal ring must paint visible pixels')
 await page.locator('.product').screenshot({path:'docs/media/player-1.3-metal-fx.png'})
 await page.getByRole('button',{name:'Pause Spotify',exact:true}).first().evaluate(b=>{window.transportButton=b})
 await page.getByRole('button',{name:'Pause Spotify',exact:true}).first().click()
 await page.getByRole('button',{name:'Play Spotify',exact:true}).first().waitFor()
 assert.equal(await page.locator('.spotify-metal canvas').count(),0,'pausing releases the artifact')
 assert.equal(await page.getByRole('button',{name:'Play Spotify',exact:true}).first().evaluate(b=>b===window.transportButton),true,'effect cleanup must not replace the playback button')
 await page.getByRole('button',{name:'Play Spotify',exact:true}).first().click()
 await page.locator('.spotify-metal canvas').waitFor()
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.waitForTimeout(300)
 assert.equal(await page.locator('.spotify-metal canvas').count(),0)
 await page.emulateMedia({reducedMotion:'no-preference'})
 await page.getByRole('tab',{name:'Visualizer',exact:true}).click()
 await page.getByLabel('Spotify audio visualizer').waitFor()
 const painted=()=>page.locator('.spotify-visualizer canvas').evaluate(c=>c.toDataURL())
 const still=await painted();await page.waitForTimeout(300)
 assert.equal(await painted(),still,'no ambient activity without a source')
 assert.ok(await page.evaluate(()=>window.demoCalls.some(c=>c.action==='/visualizer/start')),'selecting Visual starts analysis without a second enable step')
 // Deliberately synthetic test data. Production never fabricates a source.
 await page.evaluate(()=>{
  window.demoScenario['/visualizer/start']={delay:0,response:{state:'starting',lease:'fixture-spectrum'}}
  window.demoScenario['/visualizer/frame?lease=fixture-spectrum']={delay:0,response:{state:'streaming',sequence:1,bands:Array.from({length:32},(_,i)=>i<20?.65:0),wave:Array.from({length:64},(_,i)=>Math.sin(i/4)*.3),rms:.2}}
  window.demoScenario['/visualizer/stop']={delay:0,response:{state:'off'}}
 })
 await page.getByRole('tab',{name:'Artwork',exact:true}).click()
 await page.getByRole('tab',{name:'Visualizer',exact:true}).click()
 await page.locator('[data-audio-state=streaming]').waitFor()
 assert.notEqual(await painted(),still,'actual supplied FFT frame drives the pixels')
 const fixedFrame=await painted();await page.waitForTimeout(250)
 assert.equal(await painted(),fixedFrame,'unchanged audio data must not invent motion')
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.waitForTimeout(150)
 const reducedFrame=await painted();await page.waitForTimeout(250)
 assert.equal(await painted(),reducedFrame,'reduced motion freezes the visualizer')
 assert.ok(await page.evaluate(()=>window.demoCalls.some(c=>c.action==='/visualizer/stop')),'reduced motion must release the audio source')
 await page.emulateMedia({reducedMotion:'no-preference'})
 await page.locator('.product').screenshot({path:'docs/media/player-visualizer.png'})
 await page.getByRole('button',{name:'Turn screen off',exact:true}).click()
 assert.equal(await page.locator('.spotify-visualizer canvas').count(),0,'screen-off releases visualizer canvas')
 await page.getByRole('button',{name:'Turn screen on',exact:true}).click()
 await page.getByRole('button',{name:'Player settings',exact:true}).click()
 await page.getByRole('button',{name:'Taste palette',exact:true}).click()
 await page.getByRole('textbox',{name:'Playlist name',exact:true}).fill('Browser mix')
 await page.getByRole('button',{name:'Taste tracks',exact:true}).click()
 await page.getByRole('textbox',{name:'Playlist tracks',exact:true}).fill('spotify:track:aaaaaaaaaaaaaaaaaaaaaa')
 await page.getByRole('button',{name:'Taste actions',exact:true}).click()
 await page.getByRole('button',{name:'Create private playlist',exact:true}).click()
 await page.getByText('Verified · 1 track saved', {exact:true}).waitFor()
 assert.equal(await page.getByRole('link',{name:'Open playlist',exact:true}).getAttribute('href'),'https://open.spotify.com/playlist/bbbbbbbbbbbbbbbbbbbbbb')
 await page.getByRole('button',{name:'Back to taste',exact:true}).click()
 await page.getByRole('button',{name:'Like draft tracks',exact:true}).click()
 await page.getByText('Verified · 1 liked state updated',{exact:true}).waitFor()
 await page.locator('.product').screenshot({path:'docs/media/player-taste-palette.png'})
 await page.getByRole('tab',{name:'Lyrics',exact:true}).click()
 await page.getByLabel('Synced lyrics').waitFor()
 await page.evaluate(()=>{window.rafCount=0;const original=window.requestAnimationFrame;window.requestAnimationFrame=function(fn){window.rafCount++;return original.call(this,fn)}})
 await page.waitForTimeout(1200)
 assert.ok(await page.evaluate(()=>window.rafCount)<10,'lyrics must not run a frame-rate loop')
 await page.evaluate(()=>{document.querySelector('#player-pane').style.position='absolute';document.querySelector('#player-pane').style.top='-3000px'})
 await page.waitForTimeout(250)
 assert.equal(await page.locator('.spotify-metal canvas').count(),0,'offscreen pane releases GPU')
 const offscreenDraws=await page.evaluate(()=>window.drawCount)
 await page.waitForTimeout(350)
 assert.equal(await page.evaluate(()=>window.drawCount),offscreenDraws,'offscreen artifact must stop GPU draws')
 await page.evaluate(()=>{document.querySelector('#player-pane').style.position='';document.querySelector('#player-pane').style.top=''})
 await page.getByLabel('Synced lyrics').waitFor()
 await page.evaluate(()=>{document.querySelector('.product').style.width='234px';document.querySelector('#player-pane').style.height='205px'})
 await page.waitForFunction(()=>document.querySelector('.spotify-surface').getBoundingClientRect().width<235)
 assert.equal(await page.getByLabel('Synced lyrics').count(),1,'resize retains the screen selection rather than switching to a different player')
 await page.getByRole('tab',{name:'Artwork',exact:true}).click()
 // Material effects remain enabled without a separate toggle.
 assert.ok(await page.locator('#player-pane [title="After hours"]').first().evaluate(el=>el.getBoundingClientRect().width)>100,'title retains readable width in the narrow dock')
 assert.ok(await page.locator('#player-pane').evaluate(p=>{const r=p.getBoundingClientRect();return [...p.querySelectorAll('button,input')].every(e=>{const b=e.getBoundingClientRect();return b.bottom<=r.bottom+1&&b.right<=r.right+1&&b.left>=r.left-1})}),'all controls fit the narrow dock')
 await page.locator('.product').screenshot({path:'docs/media/player-1.3-standard.png'})
 await page.evaluate(()=>{document.querySelector('.product').style.width='';document.querySelector('#player-pane').style.height='280px'})
 await page.getByRole('slider',{name:'Seek Spotify',exact:true}).focus()
 const seeksBefore=await page.evaluate(()=>window.demoCalls.filter(x=>x.action==='seek').length)
 await page.keyboard.press('ArrowRight')
 await page.waitForTimeout(300)
 assert.equal(await page.evaluate(()=>window.demoCalls.filter(x=>x.action==='seek').length),seeksBefore+1,'one command per seek commit')
 assert.equal(await page.getByRole('button',{name:/visual effects/i}).count(),0,'material effects are default')
 await page.locator('.spotify-metal canvas').waitFor()
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'))})
 await page.waitForTimeout(300)
 const hiddenStart=await page.evaluate(()=>window.demoCalls.filter(x=>x.action==='status').length)
 const hiddenDraws=await page.evaluate(()=>window.drawCount)
 assert.equal(await page.locator('.spotify-metal canvas').count(),0,'background document releases artifact')
 await page.waitForTimeout(4500)
 assert.equal(await page.evaluate(()=>window.demoCalls.filter(x=>x.action==='status').length),hiddenStart,'no status requests while document hidden')
 assert.equal(await page.evaluate(()=>window.drawCount),hiddenDraws,'no GPU frames while document hidden')
 await page.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'))})
 await page.waitForTimeout(300)
 await mkdir('docs/evidence',{recursive:true})
 await page.screenshot({path:'docs/media/player-1.3-desktop.png',fullPage:true})
 await page.setViewportSize({width:390,height:844})
 await page.screenshot({path:'docs/media/player-1.3-mobile.png',fullPage:true})
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'no horizontal overflow')
 const layoutCases=[]
 await page.setViewportSize({width:1440,height:1100})
 for(const width of [234,280,320]) for(const height of [205,280,420]) for(const zoom of [1,1.25,1.5]){
   await page.evaluate(({width,height,zoom})=>{const product=document.querySelector('.product');product.style.maxWidth='none';product.style.width=width+'px';product.style.zoom=zoom;document.querySelector('#player-pane').style.height=height+'px'},{width,height,zoom})
   await page.waitForFunction(width=>Math.abs(document.querySelector('.spotify-retro-stage').offsetWidth-Math.max(234,width-2))<=2,width)
   const geometry=await page.locator('.spotify-surface').evaluate(e=>{
     const r=e.getBoundingClientRect(), title=e.querySelector('.spotify-title'), artist=e.querySelector('.spotify-artist')
     title.textContent='A deliberately long track title remains inside the original LCD';artist.textContent='A long artist name must not displace the elapsed time'
     const elements=[...e.querySelectorAll('button,input,.spotify-title,.spotify-meta,.spotify-artist,.spotify-time')]
     return {width:r.width,height:r.height,titleWidth:title.getBoundingClientRect().width,violations:elements.flatMap(c=>{const b=c.getBoundingClientRect();return b.width>0&&b.height>0&&b.left>=r.left-1&&b.right<=r.right+1&&b.top>=r.top-1&&b.bottom<=r.bottom+1?[]:[{label:c.ariaLabel||c.textContent,box:b.toJSON()}]})}
   })
   assert.ok(Math.abs(geometry.width/geometry.height-8/7)<0.005,'resizing never distorts the faceplate')
   assert.deepEqual(geometry.violations,[],JSON.stringify({width,height,zoom,geometry}))
   assert.ok(geometry.titleWidth/zoom>=100,'title never collapses')
   assert.equal(await page.getByRole('tab',{name:'Artwork',exact:true}).count(),1,'small docks retain the full retro faceplate')
   layoutCases.push({width,height,zoom,aspectRatio:'8:7',status:'passed'})
 }
 assert.equal(layoutCases.length,27)
 await writeFile('docs/evidence/layout.json',JSON.stringify({cases:layoutCases},null,2))
 await page.evaluate(()=>{const p=document.querySelector('.product');p.style.width='';p.style.zoom='';p.style.maxWidth='100%';document.querySelector('#player-pane').style.height='280px'})
 const fallback=await browser.newPage()
 fallback.on('pageerror',e=>errors.push(e.message))
 await fallback.addInitScript(()=>{
   for(const proto of [HTMLCanvasElement.prototype,OffscreenCanvas.prototype]){
     const get=proto.getContext
     proto.getContext=function(type,...args){return /webgl/.test(type)?null:get.call(this,type,...args)}
   }
 })
 await fallback.goto(`http://127.0.0.1:${server.address().port}/`)
 await fallback.getByRole('button',{name:'Pause Spotify',exact:true}).first().waitFor()
 await fallback.waitForTimeout(250)
 assert.equal(await fallback.locator('.spotify-metal canvas').count(),0,'unsupported GPU falls back without breaking the player')
 await fallback.getByRole('button',{name:'Pause Spotify',exact:true}).first().click()
 await fallback.getByRole('button',{name:'Play Spotify',exact:true}).first().waitFor()
 await fallback.close()
 assert.deepEqual(errors,[])
 await writeFile('docs/evidence/browser.json',JSON.stringify({status:'passed',statusCallsIn4800ms:calls,webglDrawsIn1100ms:draws,webglBuffer:buffer,artifact:'metal-fx@1.0.4',preset:'silver/dark',shaderExactMatch:true,webglSharedBufferMax:[96,96],hiddenStatusCallsIn4500ms:0,errors,checks:['shared polling','synchronized controls','default WebGL with motion/visibility gates','reduced motion','responsive resize','mobile overflow','offscreen GPU cleanup','seek commit','document visibility stop','WebGL frame/buffer budget','exact metal-fx shader provenance','painted ring pixels','pause/offscreen/background GPU stop','stable transport DOM','no-WebGL fallback']},null,2))
 console.log('Browser checks passed')
}catch(error){console.error('Page errors:',errors);await page.screenshot({path:'/tmp/spotify-browser-failure.png'});throw error}finally{await browser.close();server.close()}
